// This file is generated by Slice Machine. Update with care!

import Card from './Card';
import Jumbotron from './Jumbotron';

export {
	Card,
	Jumbotron,
};

export const components = {
	card: Card,
	jumbotron: Jumbotron,
};
