// This file is generated by Slice Machine. Update with care!

import Jumbotron from './Jumbotron';
import SectionForDemo from './SectionForDemo';

export {
	Jumbotron,
	SectionForDemo,
};

export const components = {
	jumbotron: Jumbotron,
	section_for_demo: SectionForDemo,
};
