name: 'main'

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  chromatic:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      # ----------------------------------------------------------

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # ----------------------------------------------------------

      - name: Publish Stories to Chromatic
        uses: chromaui/action@v1

        with:
          buildScriptName: storybook:build
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
